### ISSUE TITLE
No Emotes

### ISSUE THREAD

**Issue by ghost** [Xesyto/AdiIRC-Twitch#1]
Hey,

I installed the plugin, but I don't see any emotes, do i have to configure them somewhere?

**Comment by Stefan-v-Oudenaarden** [comment]
What version of AdiIRC do you have installed and what version of the plugin ? Additionally could use the config command "/twitch@" and see if that runs successfully ?

**Comment by ghost** [comment]
AdiIRC version: 2.8 64 bit
Plugin version: 5.2 (Downloaded the latest from Github)

The command ``/twitch@`` is working fine and shows me the following check boxes:
```
Show Timeouts/Bans
Show Cheers
Show (Re)Subscription Notification
Show Badges
```

Sometimes some badges aren't shown, I'm not sure which badges but it looks like this:
https://i.imgur.com/X3JZu47.png

Trying out emotes:
Some emotes are downloaded into ``%appdata%\Local\AdiIRC\TwitchEmotes``

 https://i.imgur.com/Az0tjIa.png 

Commands i run when i start AdiIRC 
```
/CAP REQ :twitch.tv/membership
/CAP REQ :twitch.tv/tags
/CAP REQ :twitch.tv/commands
```

**Comment by ghost** [comment]
Ooops. I had ``Emoticons`` disabled, I'm not sure if i did it or if it's a default option.

Some emotes are not being displayed like ``cmonBruh`` ``MrDestructoid`` ``BlessRNG`` ``DansGame`` etc.

https://i.imgur.com/Z6MKwV6.png

So everything is working fine now, do you have planned to implement BetterTTV and FrankerFaceZ?

**Comment by Stefan-v-Oudenaarden** [comment]
If some badges are not showing that's down to font choice. Currently I can't actually embed images / emotes in usernames hence the unicode/emoji alternative. The moment that becomes possible I'm changing to properly support all username badges. 

I'm happy everting is in working order now. 

If you have emotes that are not showing properly closing the client and reopening it should prompt them to be regenerated the first time they are used. If that fails you can try removing the emotes from the directory they are stored in and the configuration panel. 

At the moment I don't plan to implement any of the additional emote sources like BetterTTV, sorry.
