### ISSUE TITLE
Error when loading

### ISSUE THREAD

**Issue by Sundheden** [Xesyto/AdiIRC-Twitch#2]
Any ideas on what to do? http://i.imgur.com/x9ETiDD.jpg

**Comment by ghost** [comment]
Had this issue too the first time, does this error appear always? I had to remove and add the plugin again. On which version of AdiIRC and AdiIRC-Twitch are you?

**Comment by Sundheden** [comment]
Every time, I tried to reload everything, and remove and replace the files as well.

Twitch @ AdiIRC Version 5.2
Adiirc 2.8 64bit (also tried on the 32bit)

**Comment by Stefan-v-Oudenaarden** [comment]
I'm sorry  you've been having this issue. 

This article explains how to fix this problem. I'll ammend the readme. 
https://blogs.msdn.microsoft.com/drew/2009/12/23/xunit-and-td-net-fixing-the-attempt-was-made-to-load-an-assembly-from-a-network-location-problem/

**Comment by Sundheden** [comment]
Hmm, that made able to load the plugin, but now the messages appear as private conversation in another network instead of in the channel/right network-connection, all random. 
http://i.imgur.com/ZFX1o9s.jpg

(the dm convos under the network named justinfan is in fact from the network/connection named znc fran above)

But still no formatting in the original channel: http://i.imgur.com/EkOM7nb.jpg

The plugin seems to trick adiirc that the message is from another network: http://i.imgur.com/yeR2Php.png

**Comment by Stefan-v-Oudenaarden** [comment]
I honestly have no clue wtf is happening here. I run this thing all time time and I can honestly say I have never seen this or anything like it happening.

Are you using any scripts or  other plugins ? Are you connecting to twitch chat through your bouncer ? Do you know why twitches network name is reported as twitch Justinfan in your treebar instead of Twitch ?

Have you noticed any other problems or issues ?

**Comment by Stefan-v-Oudenaarden** [comment]
Could you please try turning off "Show Badges" in the options. That should stop the plugin from rewriting regular user messages. 

You should be able to access the options through the /twitch@ command or right clicking the twitch server in your treebar.

**Comment by Sundheden** [comment]
Turning off badges seems to have helped. 

The znc network is trough bouncer, and it says justinfan since I'm logged in as justinfan.

**Comment by Stefan-v-Oudenaarden** [comment]
Alright, thank you for the report. I'm going to have to dig around as to how this is happening at all. I'm closing this issue and I've opened another ( #3 ) for that specific problem.
